#!/bin/bash

INPUT_DIR="../tests/"
JCONSOLE_PATH="../j9.6/bin/jconsole"

EXCLUDE_FILES=(
  "${INPUT_DIR}programa.j"            
  "${INPUT_DIR}basics/relational_op.j"
)

# Conver files to LF format
find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
        echo "Converting 2 LF: $jfile"
        dos2unix "$jfile"
    else
        echo "Skipping: $jfile"
    fi
done

# Generate *.solve with jconsole
find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
        echo "Processing solve: $jfile"
        base_name=$(basename "$jfile" .j)
        dir_name=$(dirname "$jfile")
        output_file="${dir_name}/${base_name}.solve"
        $JCONSOLE_PATH < "$jfile" > "$output_file"
    else
        echo "Skipping: $jfile"
    fi
done

# Generate *.out with --test
find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
        echo "Processing mini J: $jfile"
        base_name=$(basename "$jfile" .j)
        dir_name=$(dirname "$jfile")
        input_file="${dir_name}/${base_name}.inp"

        (
        . venv/bin/activate
        python3 g.py --test "$jfile" < "$input_file"
        )
    else
        echo "Skipping: $jfile"
    fi
done

# Compare *.out vs *.solve, except EXCLUDE_FILES 
find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
        base_name=$(basename "$jfile" .j)
        dir_name=$(dirname "$jfile")
        output_file="${dir_name}/${base_name}.out"
        solve_file="${dir_name}/${base_name}.solve"

        echo "Comparing: $output_file vs $solve_file"
        delta "$output_file" "$solve_file" || true
    else
        echo "Skipping: $jfile"
    fi
done
