#!/bin/bash

INPUT_DIR="../tests/"
JCONSOLE_PATH="../j9.6/bin/jconsole"

find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    echo "Converting 2 LF: $jfile"
    dos2unix "$jfile"
done

find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    echo "Processing solve: $jfile"
    base_name=$(basename "$jfile" .j)
    dir_name=$(dirname "$jfile")
    output_file="${dir_name}/${base_name}.solve"
    $JCONSOLE_PATH < "$jfile" > "$output_file"
done

find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    echo "Processing mini J: $jfile"
    base_name=$(basename "$jfile" .j)
    dir_name=$(dirname "$jfile")
    input_file="${dir_name}/${base_name}.inp"
    output_file="${dir_name}/${base_name}.out"
    
    (
    . venv/bin/activate
    python3 g.py --test "$jfile" < "$input_file" > "$output_file"
    )
done

find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
    base_name=$(basename "$jfile" .j)
    dir_name=$(dirname "$jfile")
    output_file="${dir_name}/${base_name}.out"
    solve_file="${dir_name}/${base_name}.solve"

    echo "Comparing: $output_file vs $solve_file"
    delta "$output_file" "$solve_file" || true
done
