#!/bin/bash

INPUT_DIR="../tests/basics/"
JCONSOLE_PATH="../j9.6/bin/jconsole"

for jfile in "${INPUT_DIR}"*.j; do
    echo "Converting 2 LF: $jfile"
    dos2unix "$jfile"
done

for jfile in "${INPUT_DIR}"*.j; do
    echo "Processing solve: $jfile"
    base_name=$(basename "$jfile" .j)
    output_file="${INPUT_DIR}${base_name}.solve"
    $JCONSOLE_PATH < "$jfile" > "$output_file"
done

for jfile in "${INPUT_DIR}"*.j; do
    echo "Processing mini J: $jfile"
    base_name=$(basename "$jfile" .j)
    input_file="${INPUT_DIR}${base_name}.inp"
    output_file="${INPUT_DIR}${base_name}.out"
    
    (
    . venv/bin/activate
    python3 g.py --test "$jfile" < "$input_file" > "$output_file"
    )
done

for jfile in "${INPUT_DIR}"*.j; do
    base_name=$(basename "$jfile" .j)
    output_file="${INPUT_DIR}${base_name}.out"
    solve_file="${INPUT_DIR}${base_name}.solve"

    echo "Comparing: $output_file vs $solve_file"
    delta "$output_file" "$solve_file" || true
done
